### ISSUE TITLE
Check existing users

### ISSUE THREAD

**Issue by SparkyRih** [e107inc/sfs#2]
Isn't it a good idea to add a small feature to check our user DB for existing spammers?

It could be handy for those who install it for the first time, or to run every once and a while to check if some spammers still got thorugh (which were reported to SFS after they've registerd on our sites already)...

**Comment by Moc** [comment]
Will be part of the 2.1.0 release

**Comment by SparkyRih** [comment]
Wow, 8 years ago, I made this request almost 8 years ago XD

**Comment by Moc** [comment]
Haha I'm well aware. It shows the dedication of all volunteers who contribute to e107. 

Thanks for your feature request, 8 years ago.

**Comment by SparkyRih** [comment]
You're welcome :D 

But damn, I see the e107 project is still very much alive? I still have 2 websites running on like v1.0.4 or something like that (purely out of nostalgia, and one of them actually has a decent amount of information about the old "Asus Padfone", and SFS made a very big difference on that one, because it had a very active forum).

I actually need to redo one of my WordPress websites, I think I need to consider getting back to e107, maybe I can even contribute this time, because I actually got a degree in software engineering in those past 8 years :D

**Comment by Moc** [comment]
Awesome! 

Yes, e107 is very much alive. I recommend installing V2 fresh to see all its new features. 

Then when you're ready, and after taking backups, get rid of as much old plugins and themes that you no longer use. Then overwrite the existing v1 files with the latest v2 release. Go into the admin area and run the database updates and there you go!

**Comment by Moc** [comment]
Oh, and absolutely. We could definitely use your contributions!
